### ISSUE TITLE
panick : error creating pinger : if not run with root permission

### ISSUE THREAD

**Issue by GuruprasadBhatL** [bparli/fastping-rs#13]
let (tx, rx) = match transport_channel(4096, protocol) {
            Ok((tx, rx)) => (tx, rx),
            Err(e) => return Err(e.to_string()),  //  error is being returned if calling application not run with root permissions
        };

**Comment by bparli** [comment]
Realized this would be helpful to document so added to the README (#14).  Let me know if you have any further hurdles though @blguru20

**Comment by bparli** [comment]
Going to close this but let me know if you run into anymore confusions @blguru20
