### ISSUE TITLE
Incorrectly implemented identifier and sequence

### ISSUE THREAD

**Issue by k4yt3x** [bparli/fastping-rs#26]
The Wireshark capture on the left shows 10 ICMP echo requests from Linux's built-in ping utility. Notice that the identifier is fixed and the sequence number increments by one for every request sent. On the right hand side fastping-rs's capture. Both fields are randomized.

![image](https://user-images.githubusercontent.com/21986859/121587901-4833d080-ca03-11eb-92e7-51ad8abe96c7.png)

This causes some issues. In a situation where the latency is high but pinging interval is low, the responses will be matched to the wrong request. The screenshot below demonstrates what I mean. The actual latency is around 200ms.

![image](https://user-images.githubusercontent.com/21986859/121588280-ba0c1a00-ca03-11eb-8b2f-bdadf52adc23.png)

The two values on line 22 and 23 should not be randomized.

https://github.com/bparli/fastping-rs/blob/b645db039497feb7965ee2e4b4742dea69f14c48/src/ping.rs#L16-L30

**Comment by k4yt3x** [comment]
To better illustrate this issue, here's another example:

![image](https://user-images.githubusercontent.com/21986859/121617061-27cf3a80-ca32-11eb-87e2-cd04021f51f1.png)

![image](https://user-images.githubusercontent.com/21986859/121617107-3fa6be80-ca32-11eb-89f0-ba730d738ed8.png)

**Comment by bparli** [comment]
Hi @k4yt3x this should be addressed by #27 ([v0.2.3](https://crates.io/crates/fastping-rs)).  Unfortunately, [pnet](https://docs.rs/pnet/0.28.0/pnet/index.html) (which this crate depends on) will still need some changes for icmp v6 to work.  I'll see if I can get those in and add the same for icmp v6.

Hopefully, this will serve your purposes in the meantime, but let me know if not

**Comment by k4yt3x** [comment]
Thanks for fixing it.

I tried implementing it myself from the ground up at the mean time. Indeed. I haven't been able to figure out how to set identifier and sequence for ICMPv6 echo yet, maybe it just works differently in v6. I'll look more into it and see if I get it working. I'll let you know if I do.

https://github.com/k4yt3x/rustyping/blob/add87999c8fb3ad277a9378fae397ada8c7f8d3a/src/main.rs#L52-L155

Edit: this is my second program written in rust, so the code might not look pretty.
