### ISSUE TITLE
CPU burn

### ISSUE THREAD

**Issue by robbieh** [bparli/fastping-rs#5]
Thanks for writing this. I used it in a project, but it seems to always consume 100% cpu. Is there some way to throttle the ping rate so that doesn't happen?

The project I used it in is here: https://github.com/robbieh/dasblinkenping

**Comment by bparli** [comment]
Thanks for raising this.  The max_rtt argument determines the ping rate, but it looks like you already have that set past the default to 10 seconds.  I think I see whats causing the excessive CPU time so let me try a fix

**Comment by bparli** [comment]
This should be resolved with #6

**Comment by robbieh** [comment]
Oh, that's aces! It hardly registers any CPU time at all now. Thank you so much!
