### ISSUE TITLE
example from readme.md don't work correctly on windows

### ISSUE THREAD

**Issue by shkabaturd** [bparli/fastping-rs#9]
![image](https://user-images.githubusercontent.com/5405343/62367647-f41c5300-b532-11e9-865a-aa02653ef190.png)

![image](https://user-images.githubusercontent.com/5405343/62367597-cdf6b300-b532-11e9-8025-9432c5885aca.png)

**Comment by bparli** [comment]
To be honest @shkabatur I developed and tested this on ubuntu so not even sure it will work on Windows.  Did you already install winpcap (or npcap.  see [https://github.com/libpnet/libpnet#windows](https://github.com/libpnet/libpnet#windows))?

**Comment by shkabaturd** [comment]
Yes i installed it.

**Comment by bparli** [comment]
Added clarity on supported OS in readme (#14). Maybe one day Windows can be added
